### ISSUE TITLE
Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [msm8916-mainline/linux-mdss-dsi-panel-driver-generator#30] opened 2023-04-13 12:24 UTC
```
$ ./generate.sh
Generating panel drivers...
======== acer-a1-724.sh ========
Parsing: /tmp/linux-panel-drivers/dtb/acer-a1-724.dtb
Parsing: sim_video (Simulator video mode dsi panel)
Generating: sim_video (Simulator video mode dsi panel)
Parsing: hx8394d_720p_video (hx8394d 720p video mode dsi panel)
Generating: hx8394d_720p_video (hx8394d 720p video mode dsi panel)
Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension
Python runtime state: finalizing (tstate=0x00007f5e469bd638)

Current thread 0x00007f5e46a99b48 (most recent call first):
  <no Python frame>
./generate.sh: line 38: 172909 Aborted                 "$LMDPDG_DIR/lmdpdg.py" "${OPTIONS[@]}" "$DTB"
```

```
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18_alpha20230329
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
$ apk list -I | grep py3
WARNING: opening /mnt/pmbootstrap-packages: No such file or directory
py3-attrs-22.2.0-r0 x86_64 {py3-attrs} (MIT) [installed]
py3-dt-schema-2023.01-r0 x86_64 {py3-dt-schema} (BSD-2-Clause) [installed]
py3-jsonschema-4.7.2-r3 x86_64 {py3-jsonschema} (MIT) [installed]
py3-libfdt-1.6.1-r6 x86_64 {dtc} (GPL-2.0-or-later) [installed]
py3-pathspec-0.11.1-r0 x86_64 {py3-pathspec} (MPL-2.0) [installed]
py3-pyrsistent-0.19.3-r0 x86_64 {py3-pyrsistent} (MIT) [installed]
py3-rfc3987-1.3.8-r3 x86_64 {py3-rfc3987} (GPL-3.0-or-later) [installed]
py3-ruamel.yaml-0.17.21-r1 x86_64 {py3-ruamel.yaml} (MIT) [installed]
py3-ruamel.yaml.clib-0.2.7-r1 x86_64 {py3-ruamel.yaml.clib} (MIT) [installed]
py3-yaml-6.0-r2 x86_64 {py3-yaml} (MIT) [installed]
$ python -V
Python 3.11.3
```

**Comment by wonderfulShrineMaidenOfParadise** [comment] 2023-04-13 12:28
Downgrading to Alpine 3.17 seems to be a workaround.

**Comment by z3ntu** [comment] 2023-08-04 09:25
@wonderfulShrineMaidenOfParadise Can you provide how to reproduce this? So attaching dtb here or whatever else is needed

**Comment by wonderfulShrineMaidenOfParadise** [comment] 2023-08-04 20:13
`/tmp/linux-panel-drivers/dtb/acer-a1-724.dtb`, according to the outputs?
It happened on Alpine edge chroot created by pmbootstrap. I haven't checked this issue recently.

**Comment by stephan-gh** [comment] 2023-08-05 10:51
Can get that DTB at https://github.com/msm8916-mainline/linux-panel-drivers/blob/master/dtb/acer-a1-724.dtb FWIW.

**Comment by wonderfulShrineMaidenOfParadise** [comment] 2023-08-06 08:21
```
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.0
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
/ # apk list -I | grep py3
py3-libfdt-1.7.0-r1 x86_64 {dtc} (GPL-2.0-or-later) [installed]
py3-libfdt-pyc-1.7.0-r1 x86_64 {dtc} (GPL-2.0-or-later) [installed]
/ # python -V
Python 3.11.4
```

Currently unable to reproduce on latest Alpine edge with Python 3.11.4

**Comment by z3ntu** [comment] 2023-08-08 08:44
Cannot reproduce using `./lmdpdg.py acer-a1-724.dtb` on Alpine 3.18.3 (latest 3.18), Alpine edge or Arch Linux.

I fixed something similar (or same?) end of 2021: https://git.kernel.org/pub/scm/utils/dtc/dtc.git/commit/?id=d152126bb0293c321cae437bdf7437c393ee3619

Looking further, since this commit is only part of dtc v1.7.0 and the original issue was reported with dtc v1.6.1, I'm going to assume it was fixed with that.

**Closed** 2023-08-08 09:02 UTC
Labels: help wanted
